In [2]:
import numpy as np

Creating a Matrix using numpy

In [3]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [4]:
matrix_1.shape

(2, 2)

In [5]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [6]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [7]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.76913351 0.8294836  0.53237897]
 [0.3557391  0.55902983 0.57991394]
 [0.15226402 0.46030697 0.54662206]]


In [8]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(low=10,high=20,size=(4,5))
print(random_integer_matrix)

[[19 11 14 15 10]
 [15 18 11 12 10]
 [17 15 18 13 11]
 [10 11 10 13 11]]


Matrix with all the values as 1

In [9]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [11]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [12]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [14]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [16]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[ 9 95 79 35 16]
 [97 83 61 35 64]
 [53 75  0 76 55]
 [40 24 80 63 50]]


In [17]:
a.shape

(4, 5)

In [18]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[ 9 97 53 40]
 [95 83 75 24]
 [79 61  0 80]
 [35 35 76 63]
 [16 64 55 50]]


In [19]:
transpose_of_a.shape

(5, 4)

Matrix Addition

In [20]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a+b

array([[2, 4],
       [6, 8]])

In [25]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [26]:
print(matrix_1)

[[0 4 8]
 [5 3 2]
 [2 7 9]]


In [27]:
print(matrix_2)

[[ 3 15  6]
 [ 3 18 19]
 [ 1  8 19]]


In [28]:
sum = np.add(matrix_1, matrix_2)

In [29]:
print(sum)

[[ 3 19 14]
 [ 8 21 21]
 [ 3 15 28]]


Matrix Substraction

In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
a-b

array([[0, 0],
       [0, 0]])

In [30]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [31]:
diff = np.subtract(matrix_1, matrix_2)

In [32]:
print(diff)

[[  0   3  -9]
 [ -3  -3 -14]
 [ -8 -18  -7]]


Matrix Multiplication

In [22]:
# by a scalar
5*a

array([[ 5, 10],
       [15, 20]])

In [33]:
# by another matrix

matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [34]:
print(matrix_3)


[[0 2 4]
 [0 4 1]
 [4 0 4]]


In [35]:
print(matrix_4)

[[1 4 4 1]
 [4 2 2 1]
 [3 0 3 4]]


In [36]:
product = np.dot(matrix_3,matrix_4)

In [37]:
print(product)

[[20  4 16 18]
 [19  8 11  8]
 [16 16 28 20]]


In [38]:
product.shape

(3, 4)

Element wise multiplication

In [39]:
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [40]:
print(matrix_3)

[[3 4 2]
 [1 0 0]
 [1 3 4]]


In [41]:
print(matrix_4)

[[1 4 3]
 [4 2 3]
 [0 1 1]]


In [42]:
product = np.multiply(matrix_3, matrix_4)  # shape should be same
product

array([[ 3, 16,  6],
       [ 4,  0,  0],
       [ 0,  3,  4]])