In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
A

array([1, 2, 3])

In [ ]:
L

[1, 2, 3]

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)
L

[1, 2, 3, 4]

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
L


[1, 2, 3, 4]

In [ ]:
A + np.array([1,1,7])

array([ 2,  3, 10])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
A + A

array([2, 4, 6])

In [ ]:
L2 = [e*e for e in L]

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A*A

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654])

# **Dot Product**

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
a * b

array([3, 8])

In [ ]:
dot = 0
for e,f in zip(a,b):
  dot = dot+e*f

In [ ]:
dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot+=a[i]*b[i]

dot

11

In [ ]:
np.sum(a*b)

11

In [ ]:
np.dot(a,b)

11

In [ ]:
c = np.array([1,2,3])

np.cross(a,c)

array([ 6, -3,  0])

In [ ]:
a_mag = np.sqrt(np.sum(a*a))
a_mag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

# **Matrix**

In [ ]:
import numpy as np

In [ ]:
mat = [[1,2],[3,4]]
mat

[[1, 2], [3, 4]]

In [ ]:
mat[0][0]

1

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
np.sum(A[:,1])

6

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
np.dot(A,B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.dot(np.linalg.inv(A),A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
1.1+2.2==3.3

False

In [ ]:
1.2+2.2==3.4

False

In [ ]:
np.allclose(1.1+2.2,3.3)

True

In [ ]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])

In [ ]:
np.linalg.solve(A,b)

array([1500.,  700.])

# **Generating Data**

In [ ]:
np.ones((2,3))*10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.random(3)

array([0.50442271, 0.02529402, 0.62209421])

In [ ]:
np.random.random((2,3))

array([[0.57394809, 0.68345225, 0.62257079],
       [0.85156768, 0.42912444, 0.86703019]])

In [ ]:
np.random.randn(2,2)

array([[-0.48518418,  0.18469917],
       [-0.48100263, -2.18576399]])

In [ ]:
D = np.random.randn(10000)

In [ ]:
D

array([ 8.29717502e-01,  5.68393777e-02,  8.16552230e-01, ...,
        2.99112531e-04, -2.74790331e-01,  7.98521158e-02])

In [ ]:
D.mean()

0.004863823924486216

In [ ]:
D.var()

1.0452169507703084

In [ ]:
D.std()

1.0223585235964479

In [ ]:
np.sqrt(D.var())

1.0223585235964479

In [ ]:
D = np.random.randn(10000,3)

In [ ]:
D

array([[-0.20885967,  0.1699923 , -0.87515746],
       [ 0.71563669,  1.08720155,  0.74364148],
       [-0.69207647,  0.22344524, -0.95516381],
       ...,
       [ 1.79084752,  0.69070342, -0.56680233],
       [ 1.19808357, -0.62505266,  0.07395385],
       [-0.32896965, -1.46236283,  0.88191934]])

In [ ]:
np.cov(D).shape

(10000, 10000)

In [ ]:
np.random.randint(0,10,(3,3))

array([[8, 9, 3],
       [6, 1, 2],
       [2, 9, 6]])

In [ ]:
np.random.randint(78)

8