### NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [ ]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0018643929999999642


Time taken by numpy array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.00021250499999947436


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [ ]:
b.shape

(3, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones
y = np.ones((3,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)
print("\n")
a = np.eye(5,dtype=int)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
# create a numpy array with random values
b = np.random.random((5,2))
print(b)

[[0.50591935 0.57844044]
 [0.78633721 0.21633201]
 [0.59251538 0.01015246]
 [0.77682441 0.19084325]
 [0.15110859 0.16676171]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,15,(3,2))
print(c)

[[11 14]
 [12 10]
 [13 14]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[73 15 28 77 56]
 [47 12 10 84 29]
 [16 18 40 14 20]
 [53 26 39 84 62]
 [51 22 10 62 14]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[6 5 9]
 [4 4 6]
 [8 2 5]]
[[10 16 13]
 [16 12 15]
 [11 18 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 12 19]
 [14 16 21]
 [19 22 22]]
[[-11  -8 -11]
 [-14 -10 -11]
 [ -7  -4 -12]]
[[ 26  20  60]
 [  0  39  80]
 [ 78 117  85]]
[[0.15384615 0.2        0.26666667]
 [0.         0.23076923 0.3125    ]
 [0.46153846 0.69230769 0.29411765]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[2 2 4]
 [0 3 5]
 [6 9 5]]
[[13 10 15]
 [14 13 16]
 [13 13 17]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 12 19]
 [14 16 21]
 [19 22 22]]
[[-11  -8 -11]
 [-14 -10 -11]
 [ -7  -4 -12]]
[[ 26  20  60]
 [  0  39  80]
 [ 78 117  85]]
[[0.15384615 0.2        0.26666667]
 [0.         0.23076923 0.3125    ]
 [0.46153846 0.69230769 0.29411765]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 9 9]
 [3 5 9]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[6 3]
 [9 5]
 [9 9]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 1 4]
 [4 9 9]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 4]
 [1 9]
 [4 9]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(4,3))
print(a)
print(a.shape)

[[4 6 5]
 [3 2 7]
 [9 3 2]
 [1 0 3]]
(4, 3)


In [ ]:
b = a.reshape(2,6)
print(b)
print(b.shape)

[[4 6 5 3 2 7]
 [9 3 2 1 0 3]]
(2, 6)
